name: Node Publish
run-name: Node Publish [${{ github.ref_name }}] triggered by [${{ github.event_name }}/${{ github.actor }}]

on:
  release:
    types: published
  push:
    branches: '*'
  workflow_dispatch:

jobs:
  publish:
    uses: krauters/shared-workflows/.github/workflows/node-publish.yaml@b34c0968945cbd3d091d1d621effedb43029c3dd
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    with:
      node_install: true
      dry_run: ${{ github.event_name != 'release' }}
      scope: '@creo-team'
      registry_url: 'https://registry.npmjs.org'
      workspace: '@creo-team/buzz-ui'
